### ISSUE TITLE
Remove uploaded items when the user clicks View

### ISSUE THREAD

**Issue by mattiagiupponi** [geosolutions-it/geonode-importer#100]
When the user clicks the View button, e delete request should also be sent to remove the execution request. This way next time the user loads the upload page the previous uploads will be hidden if already viewed

**Comment by giohappy** [comment]
https://github.com/geosolutions-it/geonode-importer/commit/7b9ddcec16ae88772fce347773ec82feda3798f8 doesn't relate to this issue
