### ISSUE TITLE
Include a detail url for imports of single datasets

### ISSUE THREAD

**Issue by DavidQuartz** [geosolutions-it/geonode-importer#125]
Apart from GeoPackages, the other dataset imports should include a `detailUrl` in the response when the import is completed.

**Comment by mattiagiupponi** [comment]
@DavidQuartz to avoid the change of the execution_request model is it a big deal if we add the detailed URL in the output_params field?
ps: we can provide them also for the GPKG

**Comment by mattiagiupponi** [comment]
@DavidQuartz @giohappy this is what i mean:
For single layers, the payload will be:
![image](https://user-images.githubusercontent.com/51856725/194910106-c8a864c8-21d7-4e1a-abb7-b812c4e34b34.png)
 While for import for multiple layers will be:
![image](https://user-images.githubusercontent.com/51856725/194910061-cb55e23f-d031-4707-b0a3-6e8ad115abbb.png)
If needed we can also add the layer name

**Comment by giohappy** [comment]
@DavidQuartz did you stop on this?

**Comment by giohappy** [comment]
@DavidQuartz please estimate this.

**Comment by DavidQuartz** [comment]
@giohappy Currently we have a View Datasets button which links back to the catalogue page filtered to datasets. Can you clarify the requirements of the client? Since we have a list of links how would we want the client to behave.

**Comment by DavidQuartz** [comment]
> @DavidQuartz the requirement is to link directly to the dataset when only one dataset has been created. This is the behaviour of the current upload (you can see on development demo for example)

@giohappy that would mean showing a View button when the length of the url list is 1, and showing a View Datasets button it's more than 1 url?
 @mattiagiupponi Can you confirm how the url list is populated? Will there be a case where the length may be one for a while and then increase as more datasets are created in the import process (eg with gpkgs)?

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi Can you confirm how the url list is populated? Will there be a case where the length may be one for a while and then increase as more datasets are created in the import process (eg with gpkgs)?

If the requirement is to have just the URL when is a single dataset, we can return the URL only for that case and not in the case of gpkg. 
Something like this looks good @DavidQuartz ?
```json
{
    "output_params": {
        "detail_url": "/catalogue/#/dataset/{pk}"
    }
}

```

**Comment by DavidQuartz** [comment]
@mattiagiupponi so that the client will only check based on the datatype of the detail_url? Looks ok. @giohappy ?

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi so that the client will only check based on the datatype of the detail_url? Looks ok. @giohappy ?

@DavidQuartz when u mean "on the datatype of the detail_url"?
Is easier... if the detail_url is there u can get it and show the button otherwise no (we are not going to add the URL if is more than 1 dataset)

**Comment by DavidQuartz** [comment]
I would estimate a few hours if the backend is ready
