### ISSUE TITLE
Please edit file name

### ISSUE THREAD

**Issue by S-Suraphat** [geosolutions-it/geonode-importer#136]
Please edit file name of `importer/tests/fixture/KML_Samples.kml:Zone.Identifier` to avoid invalid path issue on some system

![image](https://user-images.githubusercontent.com/18545770/197697321-d3b0274d-e9a0-45ef-b50d-b6f9a8f864ca.png)

**Comment by giohappy** [comment]
Thanks @S-Suraphat. The file has been deleted.
