### ISSUE TITLE
UTF8 encoding error when importing a shepefile

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-importer#139]
Importing [this shapefile](https://github.com/geosolutions-it/geonode-importer/files/9902501/US.cities.zip)  works fine the current imported (you can see it on development demo).
The new imported throws the following error:

![image](https://user-images.githubusercontent.com/571129/199046125-57e2957c-3a36-482e-b857-4832d292b57a.png)

**Comment by mattiagiupponi** [comment]
Hi @giohappy 
I reproduced the bug on my local env for the import phase, and ogr2ogr raised this issue:
```bash
Exception: b"Warning 6: dataset PG: dbname='geonode_data' host=localhost port=5434 user='geonode' password=XXXXXXXXX  
does not support layer creation option ENCODING\nERROR 1: Non UTF-8 content found when writing feature -1 of layer 
bx729wr3020: 010100002032BF0D00DF65AEC21C775AC095CC295CEACB4140\t918094.000000000000000\t2407951\tCensus\t-999\tCa\xf1ada de los Alamos\t434.000000000000000
\tSanta Fe\t049\tNM\t35\t35.593089599999999\t-105.861130399999993\t35.593089599999999\t-105.861130399999993\t2305.000000000000000\t7562.000000000000000\n\n
ERROR 1: Unable to write feature 17767 from layer bx729wr3020.\nERROR 1: 
Terminating translation prematurely after failed\ntranslation of layer bx729wr3020 (use -skipfailures to skip errors)\n" for layer bx729wr3020
```

It looks like that one specific feature is not in UTF-8 so ogr2ogr raises the issue.
Analyzing the features better, I can see that the nr°17767 is not in UTF-8 format:
![image](https://user-images.githubusercontent.com/51856725/199456402-40e9dd84-95f6-4aa0-bff4-7435f9fcf7f6.png)

On the development demo, it looks like that GeoServer saves it without taking much care of the encoding:
![image](https://user-images.githubusercontent.com/51856725/199456974-bc538471-5484-4999-b889-f92685196cd4.png)

I'll analyze deeper the possibilities more, but for a quick fix, we can add the [-skipfailures](https://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-skipfailures) that ogr2ogr provides to skip the failing features.

**Comment by giohappy** [comment]
Silent failures is not a good solution imho, since the users will ignore that some features have been silently dropped.

I would rather inprove the error message, making it sloghtly less technical. We can include the exception details, but I woul start simply saying that the file couldn't be imported, and improving the formatting of the message.

**Comment by mattiagiupponi** [comment]
> Silent failures is not a good solution imho, since the users will ignore that some features have been silently dropped.

i agree

> I would rather improve the error message, making it slightly less technical. We can include the exception details, but I would start simply by saying that the file couldn't be imported and improving the formatting of the message.

I'll see what I can do, unlucky is a error message returned by ogr2ogr

**Comment by giohappy** [comment]
>I'll see what I can do, unlucky is a error message returned by ogr2ogr

I know, but we can wrap it in a more informative (and well formatted) message for the end user.

**Comment by giohappy** [comment]
At least it is almosr human teadable now :)
