### ISSUE TITLE
Error with a shapefile that works well with the Geoserver importer

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-importer#151]
The upload of [this shapefile](https://github.com/geosolutions-it/geonode-importer/files/10175253/Italy_2019.zip) raises the following error:

`Task: importer.import_with_ogr2ogr raised an error during actions for layer: reg01012019_g_wgs841: ERROR 1: Layer , ERROR 1: Terminating translation prematurely after failed for layer reg01012019_g_wgs841`

**Comment by mattiagiupponi** [comment]
@giohappy I tried several datasets (shp, gpkg, kml) along with the one in the issue and none of them raises the issue.

I check the differences between my environment ad the development demo and I guess is a matter of gdal-version.

development demo

```
root@6b6eb9c56bc6:/usr/src/geonode_master# gdalinfo --version
GDAL 3.2.2, released 2021/03/05
```

My env

```
➜  user gdalinfo --version
GDAL 3.4.3, released 2022/04/22
```

I guess here is that we have to evaluate an upgrade of the gdal provided in the geonode-compose file so align to a more recent version. This might be enough to solve the issue

**Comment by giohappy** [comment]
Unfortunately, we're using Debian 11 apt repos, which ship with GDAL 3.2.2.
Given that we're using a Debian 10 images (which is out of LTS now) it could be right time to make the jump to Ubuntu 22.04, where we have GDAL 3.4.1

**Comment by mattiagiupponi** [comment]
as we tested on development-demo, the issue looks fixed after the gdal update.
