### ISSUE TITLE
Implement rollback function

### ISSUE THREAD

**Issue by mattiagiupponi** [geosolutions-it/geonode-importer#162]
In case of any issue, the non-completed import should be rollbacked.
To achieve this, we need to implement the following thing:

- each celery task should call the orchestrator in case of failure. The call will have an additional boolean param called `rollback`. 
- The orchestrator in case of a rollback should call the `rollback` method exposed by the handler by passing the step that raises the error and which type of action was done (import/copy)
- The handler based on the input step/action should rollback the current and previous actions already performed

**Comment by giohappy** [comment]
@mattiagiupponi what about having a `rollback` step, instead of a flag?

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi what about having a `rollback` step, instead of a flag?

Yep we can do It.
In this case we can also use the actual structure by:
- define for each handler the rollback step
- define a celery task that call the handler rollback function
- let the orchestrator use the actual workflow


In the end we will call the importer_next_step by using ROLLBACK as action

**Comment by giohappy** [comment]
@mattiagiupponi please assign an estimate for this task.
