### ISSUE TITLE
importer benchmark and stresstests

### ISSUE THREAD

**Issue by mattiagiupponi** [geosolutions-it/geonode-importer#44]

**Comment by giohappy** [comment]
@mattiagiupponi I would try to make some more tests with exceptional conditions like:

 - DB connection reset / closed during the executions
 - Geoserver not responding
 - Celery not elaborating queues (it happened recently due to Rabbit gone crazy on development demo)

**Comment by mattiagiupponi** [comment]
At the moment it takes into consideration just 1 tentative (since we were talking about having a rollback per phase), we can discuss it and how to handle the errors, btw I can reply to those points without trying

> * DB connection reset / closed during the executions

As soon as in the first stage (creation of  the dynamic model, import of the ogr2ogr resource, or creation of the fields) in case of any error (db reset included) all the data are rollbacked (dynamic model/fields and table are deleted)

> * Geoserver not responding

as I said only one tentative is done, if during the publishing something happens the execution is set into a FAILED state. 
If, is during the geonode phase (since now the resource manager is still performing interaction with GS) the error is ignored and the resource is created

> * Celery not elaborating queues (it happened recently due to Rabbit going crazy on the development demo)

This could be quite challenging... i need some time to think about this

**Comment by giohappy** [comment]
>as I said only one tentative is done, if during the publishing something happens the execution is set into a FAILED state.

Only one tentative? Aren't we retrying here?

>If, is during the geonode phase (since now the resource manager is still performing interaction with GS) the error is ignored and the resource is created

Why can't we capture errors happening during the geonode phase? Even if they aren't under the explicit control of the orchestrator I guess they can be handled, no? Are they trapped by internal code?

**Comment by mattiagiupponi** [comment]
> Only one tentative? Aren't we retrying here?

Not now, but I'm going to add the retry on GeoServer publishing, it should be quite easy
 
> Why can't we capture errors happening during the geonode phase? Even if they aren't under the explicit control of the orchestrator I guess they can be handled, no? Are they trapped by internal code?

Yes, internally geonode handle it so is not raised from a task point of view
