### ISSUE TITLE
Evaluate the implementation of a raster handler

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/geonode-importer#59]
Raster import could be implemented in way similar to vectors, using a shared volume from which the raster file could be published.

This approach needs careful analysis of the implications, although I don't see blockers.

Meanwhile the current importer-based flow could be wrapped inside a geonode-importer handler. This way we could get rid of the old implementation, both upload and import.

@etj @mattiagiupponi opinions?

**Comment by mattiagiupponi** [comment]
> Raster import could be implemented in way similar to vectors, using a shared volume from which the raster file could be published.

The handler now contains all the methods needed to import and publish the resource

> Meanwhile the current importer-based flow could be wrapped inside a geonode-importer handler. This way we could get rid of the old implementation, both upload, and import.

Yes, thanks to the creation of the registry, we can set which kind of file the new importer can handle, so once the handler is ready is enough to register the new app here https://github.com/geosolutions-it/geonode-importer/blob/d92d796d485366ae6f693d08e728523ef5e09d4e/importer/handlers/apps.py#L14-L16

> This approach needs careful analysis of the implications, although I don't see blockers.

Indeed, the main sensitive point is related to where to store these images. I suggest adding a settings/env_var to configure the path outside the normal upload folder. The storage manager may need an improvement to clone the files into a different directory from the standard one by adding a param [here](https://github.com/GeoNode/geonode/blob/f680e131e55e6cf5f8a474989ec40be15673909b/geonode/storage/manager.py#L243)

**Comment by mattiagiupponi** [comment]
TODO:
1. To be decided the usage of [rasterio](https://rasterio.readthedocs.io/en/latest/index.html) to handle the raster files. Maybe is better to continue with ogr2ogr with its [drivers](https://gdal.org/drivers/raster/index.html) to avoid the usage of too many libraries
1. Change the storage manager to le the destination folder of the clone being bookable. This is needed for example if we want to store the images in the non-default upload path:
The changes must be done in the [storage manager](https://github.com/GeoNode/geonode/blob/762c7c970c23e9f910bd6105199636400d749609/geonode/storage/manager.py#L239-L243) and the [data-retriever](https://github.com/GeoNode/geonode/blob/762c7c970c23e9f910bd6105199636400d749609/geonode/storage/data_retriever.py#L74-L80)
1. To be analyzed if `smart_open` can save the file in another destination (even in another container if needed)
1. create a "raster" handler. Probably it will contain less customization than the vector, it will be unique unless validation for each format is required
1. basic validation is needed
1. publish the resource in geoserver, probably this [method is needed](https://github.com/GeoNode/geoserver-restconfig/blob/master/src/geoserver/catalog.py#L552)
1. the creation of the geonode resource and the dynamic model
1. handle the "copy" of the resource
1. Test coverage with unittest and end2end testing

Integration:
1. Test with docker instances and relative volume share (this test may require different changes in the code to let it possible)
2. Fix project docker-compose to let the volume be visible between the two instances (Geonode/Geoserver) (it may be needed the support of a DevOps)

Estimation without docker: 13 (~ 1 week)
Estimation with docker: 18 (~ 1 and 1/2 week)

@giohappy can I proceed?
